// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kewbzzypfcqfioqjpmup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtld2J6enlwZmNxZmlvcWpwbXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMTM4MzMsImV4cCI6MjA2MjU4OTgzM30.ayuv2KCPAv0lbM6GnHKClwACzvZT7hdTl9ak9tr_VjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);